algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

valor,contador:inteiro

inicio
contador<-0
escreva("Até quanto deseja contar? ")
leia(valor)
enquanto (contador<=valor) faca
   escreval(contador)
   contador<-contador+1
fimenquanto

fimalgoritmo