algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

V1,V2,N,S,C:inteiro

inicio

v1<-0
v2<-1
escreva("Informe um valor: ")
leia(N)

para C<-1 ate N faca
    S<-V1+V2
    escreva(S,"..")
    v1<-v2
    v2<-S
fimpara


fimalgoritmo